version: "3"

x-logging:
  &default-logging
  options:
    max-file: '1'
    compress: 'false'
  driver: local

networks:
  autonity_network:
    name: autonity_network

services:
  autonity:
    image: autonity-git:latest
    container_name: autonity
    restart: always
    networks:
      autonity_network:
        ipv4_address: ${DOCKER_SUBNET_PREFIX}.2
    ports:
      - ${SECURE_NETWORK_IP}:8545:8545
      - ${SECURE_NETWORK_IP}:8546:8546
      - 30303:30303
      - 30303:30303/udp
      - ${SECURE_NETWORK_IP}:6060:6060 #PPROF
      - ${SECURE_NETWORK_IP}:6064:6064 #PROMETHEUS
    volumes:
      - ./.data/autonity_node:/autonity-chaindata
      - ./.data/.autonity:/root/.autonity
    build:
      context: ./src/docker/autonity/
      dockerfile: Dockerfile
    command:
      - --datadir=/autonity-chaindata
      - --${NETWORK_NAME}
      - --http
      - --http.addr=0.0.0.0
      - --http.api=aut,eth,net,txpool,web3,admin
      - --http.vhosts=*
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.api=aut,eth,net,personal,txpool,web3,admin
      - --nat=extip:${EXTERNAL_IP}
      - --metrics
      - --metrics.addr=0.0.0.0
      - --metrics.port=6064
      - --metrics.expensive
      - --pprof

  autonity_oracle:
    image: autonity-oracle-git:latest
    container_name: autonity_oracle
    restart: always
    build:
      context: ./src/docker/autoracle/
      dockerfile: Dockerfile.${NETWORK_NAME}
    networks:
      autonity_network:
        ipv4_address: ${DOCKER_SUBNET_PREFIX}.3
    volumes:
      - ./.data/autonity_oracle:/autoracle
      - ./.data/.autonity/keystore:/autonity_keystore
#      - ./.data/.autonity/keystore/${ORACLE_UTC_FILE}:/oracle.key:ro
    command:
      - -key.file=/autonity_keystore/oracle.key
      - -key.password=${ORACLE_KEY_PASSWD}
      - -ws=ws://autonity:8546
      - -plugin.dir=/usr/local/bin/plugins/
      - -plugin.conf=/autoracle/plugins-conf.yml

  aut_client:
    image: aut_client:${AUTONITY_AUT_CLIENT}
    container_name: aut_client
    restart: always
    volumes:
      - ./.data/.autonity:/root/.autonity
#      - ./.data/.autonity/.autrc:/.autrc
      - ./.data/autonity_node/autonity:/root/autonity_node
    networks:
      autonity_network:
        ipv4_address: ${DOCKER_SUBNET_PREFIX}.4
    build:
      context: ./src/docker/aut_client/
      dockerfile: Dockerfile
